/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import Controler.Click;
import Controler.GameControl;
import static java.lang.System.exit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author SUPUN
 */
public class GameWindow extends javax.swing.JFrame {

    /**
     * Creates new form GameWindow
     */
    private static GameControl control;
    private ImageIcon zero;
    private ImageIcon cross;
     private Click game;
     private int enable[];
    public GameWindow(GameControl control) {
        initComponents();
        this.control=control;
        this. game=new Click();
        enable=new int[9];
        zero=new ImageIcon(getClass().getResource("/Imege/Zero.png"));
        cross=new ImageIcon(getClass().getResource("/Imege/cross.png"));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        win = new javax.swing.JLabel();
        win2 = new javax.swing.JLabel();
        grid1 = new javax.swing.JLabel();
        grid2 = new javax.swing.JLabel();
        grid3 = new javax.swing.JLabel();
        grid4 = new javax.swing.JLabel();
        grid5 = new javax.swing.JLabel();
        grid6 = new javax.swing.JLabel();
        grid7 = new javax.swing.JLabel();
        grid8 = new javax.swing.JLabel();
        grid9 = new javax.swing.JLabel();
        Retry = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        Quit = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        Name2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(342, 500));
        setMinimumSize(new java.awt.Dimension(342, 500));
        getContentPane().setLayout(null);

        win.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        win.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(win);
        win.setBounds(120, 20, 50, 30);

        win2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        win2.setForeground(new java.awt.Color(0, 102, 255));
        getContentPane().add(win2);
        win2.setBounds(300, 20, 40, 30);

        grid1.setBackground(new java.awt.Color(48, 10, 10));
        grid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grid1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid1MouseClicked(evt);
            }
        });
        getContentPane().add(grid1);
        grid1.setBounds(80, 180, 50, 50);

        grid2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid2MouseClicked(evt);
            }
        });
        getContentPane().add(grid2);
        grid2.setBounds(140, 180, 50, 50);

        grid3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid3MouseClicked(evt);
            }
        });
        getContentPane().add(grid3);
        grid3.setBounds(210, 174, 50, 50);

        grid4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid4MouseClicked(evt);
            }
        });
        getContentPane().add(grid4);
        grid4.setBounds(74, 244, 50, 50);

        grid5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid5MouseClicked(evt);
            }
        });
        getContentPane().add(grid5);
        grid5.setBounds(144, 244, 50, 50);

        grid6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid6MouseClicked(evt);
            }
        });
        getContentPane().add(grid6);
        grid6.setBounds(214, 244, 50, 50);

        grid7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid7MouseClicked(evt);
            }
        });
        getContentPane().add(grid7);
        grid7.setBounds(80, 314, 50, 50);

        grid8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid8MouseClicked(evt);
            }
        });
        getContentPane().add(grid8);
        grid8.setBounds(144, 310, 50, 50);

        grid9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grid9MouseClicked(evt);
            }
        });
        getContentPane().add(grid9);
        grid9.setBounds(214, 314, 50, 50);

        Retry.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        Retry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Retry.setText("RETRY");
        Retry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetryMouseClicked(evt);
            }
        });
        getContentPane().add(Retry);
        Retry.setBounds(70, 390, 200, 30);

        Back.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(10, 440, 100, 20);

        Quit.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        Quit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quit.setText("Quit");
        Quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitMouseClicked(evt);
            }
        });
        getContentPane().add(Quit);
        Quit.setBounds(250, 440, 90, 20);

        Name1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(Name1);
        Name1.setBounds(10, 20, 100, 30);

        Name2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(Name2);
        Name2.setBounds(200, 20, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imege/help.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 24, 70, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imege/help.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 24, 70, 30);

        main.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.disabledForeground"));
        main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imege/Game.jpg"))); // NOI18N
        main.setText("jLabel1");
        getContentPane().add(main);
        main.setBounds(0, 0, 342, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grid1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid1MouseClicked
        if(enable[0]==0){
            game.changePlayer();
            if(Click.player==-1){
                grid1.setIcon(zero);
            }
            else{
                grid1.setIcon(cross);
            }
            game.playerClick(1);
            game.checkPlayWin();
            enable[0]=1;
            if(Click.win==1){
            disableGrid();
            }
            
        }
    }//GEN-LAST:event_grid1MouseClicked

    private void grid2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid2MouseClicked
        // TODO add your handling code here:
        
        if(enable[1]==0){
        game.changePlayer();
        if(Click.player==-1){
            grid2.setIcon(zero);
        }
        else{
            grid2.setIcon(cross);
        }
        game.playerClick(2);
        game.checkPlayWin();
           enable[1]=1;
         if(Click.win==1){
            disableGrid();
            }  
        }
    }//GEN-LAST:event_grid2MouseClicked

    private void grid3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid3MouseClicked
        // TODO add your handling code here:
        
        if(enable[2]==0){
        game.changePlayer();
        if(Click.player==-1){
            grid3.setIcon(zero);
        }
        else{
            grid3.setIcon(cross);
        }
        game.playerClick(3);
        game.checkPlayWin();
        enable[2]=1;
        if(Click.win==1){
            disableGrid();
        }
        }
        
        
    }//GEN-LAST:event_grid3MouseClicked

    private void grid4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid4MouseClicked
        // TODO add your handling code here:
        if(enable[3]==0){
        game.changePlayer();
        if(Click.player==-1){
            grid4.setIcon(zero);
        }
        else{
            grid4.setIcon(cross);
        }
        game.playerClick(4);
        game.checkPlayWin();
        enable[3]=1;
        if(Click.win==1){
            disableGrid();
        }
        }
    }//GEN-LAST:event_grid4MouseClicked

    private void grid5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid5MouseClicked
        // TODO add your handling code here:
        if(enable[4]==0){
        game.changePlayer();
        if(Click.player==-1){
            grid5.setIcon(zero);
        }
        else{
            grid5.setIcon(cross);
        }
        game.playerClick(5);
        game.checkPlayWin();
        enable[4]=1;
        if(Click.win==1){
            disableGrid();
        }
        }
    }//GEN-LAST:event_grid5MouseClicked

    private void grid6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid6MouseClicked
        // TODO add your handling code here:
        if(enable[5]==0){
        game.changePlayer();
        if(Click.player==-1){
            grid6.setIcon(zero);
        }
        else{
            grid6.setIcon(cross);
        }
        game.playerClick(6);
        game.checkPlayWin();
        enable[5]=1;
        if(Click.win==1){
            disableGrid();
        }
        }
    }//GEN-LAST:event_grid6MouseClicked

    private void grid7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid7MouseClicked
        // TODO add your handling code here:
        if(enable[6]==0){
        game.changePlayer();
        if(Click.player==-1){
            grid7.setIcon(zero);
        }
        else{
            grid7.setIcon(cross);
        }
        game.playerClick(7);
        game.checkPlayWin();
        enable[6]=1;
        if(Click.win==1){
            disableGrid();
        }
        }
    }//GEN-LAST:event_grid7MouseClicked

    private void grid8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid8MouseClicked
        // TODO add your handling code here:
        if(enable[7]==0){
        game.changePlayer();
        if(Click.player==-1){
            grid8.setIcon(zero);
        }
        else{
            grid8.setIcon(cross);
        }
        game.playerClick(8);
        game.checkPlayWin();
        enable[7]=1;
        if(Click.win==1){
            disableGrid();
        }
        }
    }//GEN-LAST:event_grid8MouseClicked

    private void grid9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid9MouseClicked
        // TODO add your handling code here:
        if(enable[8]==0){
        game.changePlayer();
        if(Click.player==-1){
            grid9.setIcon(zero);
        }
        else{
            grid9.setIcon(cross);
        }
        game.playerClick(9);
        game.checkPlayWin();
        enable[8]=1;
        if(Click.win==1){
            disableGrid();
        }
        }
    }//GEN-LAST:event_grid9MouseClicked

    private void RetryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetryMouseClicked
        // TODO add your handling code here:
        
        for (int i = 0; i < 9; i++) {
            enable[i]=0;
            
        }
        disableImege();
        game.clearData();
        
        
        
        
    }//GEN-LAST:event_RetryMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        
        control.showChooseWindow();
        RetryMouseClicked(evt);
        control.closeGameWindow();
    }//GEN-LAST:event_BackMouseClicked

    private void QuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitMouseClicked
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_QuitMouseClicked
    public void disableImege(){
        grid1.setIcon(null);
        grid2.setIcon(null);
        grid3.setIcon(null);
        grid4.setIcon(null);
        grid5.setIcon(null);
        grid6.setIcon(null);
        grid7.setIcon(null);
        grid8.setIcon(null);
        grid9.setIcon(null);
    }
    public void setName(){
        Name1.setText(control.getPlayer1Name());
        Name2.setText(control.getPlayer2Name());
        win.setText(Integer.toString(Name.winPlayer1));
        win2.setText(Integer.toString(Name.winPlayer2));
        
    }
    public void disableGrid(){
        win.setText(Integer.toString(Click.win1));
        win2.setText(Integer.toString(Click.win2));
        for (int i = 0; i < 9; i++) {
            enable[i]=1;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow(control).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Quit;
    private javax.swing.JLabel Retry;
    private javax.swing.JLabel grid1;
    private javax.swing.JLabel grid2;
    private javax.swing.JLabel grid3;
    private javax.swing.JLabel grid4;
    private javax.swing.JLabel grid5;
    private javax.swing.JLabel grid6;
    private javax.swing.JLabel grid7;
    private javax.swing.JLabel grid8;
    private javax.swing.JLabel grid9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel main;
    private javax.swing.JLabel win;
    private javax.swing.JLabel win2;
    // End of variables declaration//GEN-END:variables
}
