/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import Controler.GameControl;
import DBConnection.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SUPUN
 */
public class Name extends javax.swing.JFrame {

    /**
     * Creates new form Name
     */
    private static GameControl control;
    public static String Play1Name;
    public static String Play2Name;
    public static int winPlayer1=0;
    public static int winPlayer2=0;
    private static int winPlayer=0;
    public Name(GameControl control) {
        initComponents();
        this.control=control;
        jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(409, 305));
        setMinimumSize(new java.awt.Dimension(409, 305));
        setPreferredSize(new java.awt.Dimension(420, 325));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        jLabel2.setText("PLAYER 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 140, 100, 30);

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        jLabel3.setText("PLAYER 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 190, 100, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 140, 200, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 190, 200, 30);

        jButton1.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 250, 73, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imege/data.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 409, 305);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        Play2Name=jTextField2.getText();
        jButton1.setEnabled(true);
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
            Play1Name=jTextField1.getText();
            jTextField2.requestFocus();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(serchName(Play1Name)==1){
            setName(Play1Name);
        
        }
        winPlayer1=winPlayer;
        
        if(serchName(Play2Name)==1){
            setName(Play2Name);
        
        }
        winPlayer2=winPlayer;
        control.setPlayer1Name(Play1Name);
        control.setPlayer2Name(Play2Name);
        
        control.closeNameWindow();
        
        control.showGameWindow();
        jTextField1.setText(null);
        jTextField2.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed
    public int serchName(String name){
        int check=0;
        String sql ="select * from player where name='"+name+"';";
        
        try {
            Connection connection = DBConnection.getInstance().getConnection();
            Statement stm = connection.createStatement();
            ResultSet rst = stm.executeQuery(sql);
            rst.next();
            if(rst.getInt("Win_Score")==0){
                check=1;
                winPlayer=0;
            }
            else{
                winPlayer=rst.getInt("Win_Score");
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Name.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Name.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        return check;
    }
    public void setName(String name){
        
        String sql ="insert into Player values('"+name+"',"+"0,0);";
        
        try {
            Connection connection = DBConnection.getInstance().getConnection();
            Statement stm = connection.createStatement();
            stm.executeUpdate(sql);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Name.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Name.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Name.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Name(control).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
